name: ci

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - uses: extractions/setup-just@v3

      - uses: sourcemeta/jsonschema@v16.2.1

      - name: Test
        run: just test